sonar.projectKey=incredible-india-tourism
sonar.projectName=Incredible India Tourism App
sonar.projectVersion=1.0

sonar.sources=app.py,templates
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/data/**
sonar.coverage.exclusions=tests/**

# Quality Gate thresholds
sonar.qualitygate.wait=true